server:
  port: 8081
logging:
  level:
    root: info
    iu.edu.popUp: debug
  file: logs/app.log
spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/popup?verifyServerCertificate=false&useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123asdfgh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true